### PR TITLE
feat: admin functionality - disable user

### PR DESCRIPTION
**Pull request by minjnlgc**
In Admin Dashboard:
- Change the key for disabling a user from `r` to `i` (since `r` is reserved for "return").
- Created `_print_users_with_disabled_status` in the `adminService` class as a private method, since it's only used by the `adminService` to show account status.
   -  it will not show admin account
- Not allow to delete admin account

In Patient and GP Dashboards:
- Only display the "Log out" option if the current user's account is disabled.
- Create a function `show_disabled_account_dashboard_menu` to handle this behavior, making it reusable.

### CODE REVIEW

**Review by ben-jthompson — DISMISSED** [review]
Code is robust and looks good on both admin side and patient side. Just brainstorming, would we require a function which could let the disabled user message/reach the admin? Or are we expecting that that functionality happens outside of the app? Otherwise, the code looks great.

**Comment by minjnlgc** [comment]
> Code is robust and looks good on both admin side and patient side. Just brainstorming, would we require a function which could let the disabled user message/reach the admin? Or are we expecting that that functionality happens outside of the app? Otherwise, the code looks great.

Good idea! I think that could be an additional feature we could add after implementing the basic functionality

**Comment by rheahemmadi** [comment]
Works for me! Only thing is that when I disable a user, it then asks me again to enter a username so I have to click R to cancel and then B to get back to dashboard. Would it be better to go back to dashboard straight after disabling a user, rather than asking if they want to disable another user immediately?

**Comment by minjnlgc** [comment]
> Works for me! Only thing is that when I disable a user, it then asks me again to enter a username so I have to click R to cancel and then B to get back to dashboard. Would it be better to go back to dashboard straight after disabling a user, rather than asking if they want to disable another user immediately?

Thank you for your feedback! My thinking is that if the user wants to disable multiple users, they don't have to go back to the dashboard and select 'disabled user' multiple times

**Review by rheahemmadi — APPROVED** [review]
Approved, happy with logic to let them disable many at users in one go without going back to dashboard

**Pull request merged**
